title: Jekyll gallery by CloudCannon
author: Ross Phillips
description: Free images, more appearing every now and then.
baseurl: "" # the subpath of your site, e.g. /gallery/

collections:
  pictures:
    output: true

defaults:
  -
    scope:
      path: ""
      type: pictures
    values:
      layout: picture
